# Generated by Django 5.0.1 on 2024-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=('default.jpg', 'default.png'), upload_to='profile_pics'),
        ),
    ]
